# name: Review

# on:
#   # Trigger the workflow on activity over any pull request to main:
#   pull_request:
#     branches:
#       - main

# # Generate a GitHub token that can be exchanged with Google Cloud - see
# # https://github.com/google-github-actions/auth/tree/v0.6.0#setting-up-workload-identity-federation
# permissions:
#   contents: read
#   id-token: write
#   deployments: write

# jobs:
#   google-test-and-build:
#     if: ${{ github.actor != 'dependabot[bot]' }}
#     name: Google Integration
#     uses: ./.github/workflows/test-and-build.yml
#     with:
#       deploy_name: staging
#       gcloud_service_account: github-actions-runner@icalialabs-staging.iam.gserviceaccount.com
#       gcloud_workload_identity_provider: projects/88514678916/locations/global/workloadIdentityPools/ci-workload-pool/providers/github
#     secrets: inherit

#   google-release-to-review:
#     if: ${{ github.actor != 'dependabot[bot]' }}
#     name: Google Delivery
#     uses: ./.github/workflows/deploy-to-cloud-run.yml
#     needs:
#       - google-test-and-build
#     with:
#       environment: ${{ github.head_ref }}
#       deploy-name: pr${{ github.event.pull_request.number }}
#       marketing-url-api: marketing-url-api:latest
#       bucket-name: workspace-bucket-name:latest
#       bucket-credentials: workspace-bucket-json-credentials:latest
#       cloud-sql-instance: icalialabs-staging:us-central1:postgres-dev-a
#       cloud-sql-username-secret: workspace-db-username:latest
#       cloud-sql-password-secret: workspace-db-password:latest
#       cloud-run-service-suffix: ${{ needs.google-test-and-build.outputs.git-commit-short-sha }}
#       cloud-run-container-image: us-central1-docker.pkg.dev/icalialabs-staging/app/workspace-icalialabs-com-backend@${{ needs.google-test-and-build.outputs.container-image-digest }}
#       potentia-host: workspace-potentia-host:latest
#       github_projects_token: operations-github-token:latest
#       gcloud_service_account: github-actions-runner@icalialabs-staging.iam.gserviceaccount.com
#       gcloud_workload_identity_provider: projects/88514678916/locations/global/workloadIdentityPools/ci-workload-pool/providers/github
#       gcloud_project: icalialabs-staging
#     secrets: inherit

#   azure-test-and-build:
#     if: ${{ github.actor != 'dependabot[bot]' }}
#     name: Azure Integration
#     uses: ./.github/workflows/azure-test-and-build.yml
#     with:
#       deploy-name: pr${{ github.event.pull_request.number }}
#       resource-group-name: WorkspaceIcaliaLabs
#       app-name: workspace-backend-
#     secrets: inherit

#   azure-release-to-review:
#     if: ${{ github.actor != 'dependabot[bot]' }}
#     name: Azure Delivery
#     uses: ./.github/workflows/azure-deploy.yml
#     needs:
#       - azure-test-and-build
#     with:
#       plan-name: WorkspaceFreePlan
#       environment: ${{ github.head_ref }}
#       deploy-name: pr${{ github.event.pull_request.number }}
#       resource-group-name: WorkspaceIcaliaLabs
#       azure-acr-container-image: workspaceapps.azurecr.io/workspace-backend-pr${{ github.event.pull_request.number }}@${{ needs.azure-test-and-build.outputs.container-image-digest }}
#       app-name: workspace-backend-
#       create-database: true
#     secrets: inherit
