# name: CI & CD Production

# on:
#   release:
#     types:
#       - published

# # Generate a GitHub token that can be exchanged with Google Cloud - see
# # https://github.com/google-github-actions/auth/tree/v0.6.0#setting-up-workload-identity-federation
# permissions:
#   contents: read
#   id-token: write
#   deployments: write

# jobs:
#   google-test-and-build:
#     name: Google Integration
#     uses: ./.github/workflows/test-and-build.yml
#     with:
#       deploy_name: production
#       gcloud_service_account: github-actions-runner@icalialabs-production.iam.gserviceaccount.com
#       gcloud_workload_identity_provider: projects/461892963202/locations/global/workloadIdentityPools/ci-workload-pool/providers/github
#     secrets: inherit

#   google-deploy-to-production:
#     name: Google Production deployment
#     uses: ./.github/workflows/deploy-to-cloud-run.yml
#     needs:
#       - google-test-and-build
#     with:
#       environment: production
#       deploy-name: production
#       marketing-url-api: marketing-url-api:latest
#       bucket-name: workspace-bucket-name:latest
#       bucket-credentials: workspace-bucket-json-credentials:latest
#       cloud-sql-instance: icalialabs-production:us-central1:postgres-dev-a
#       cloud-sql-username-secret: workspace-db-username:latest
#       cloud-sql-password-secret: workspace-db-password:latest
#       cloud-run-service-suffix: ${{ needs.google-test-and-build.outputs.git-commit-short-sha }}
#       cloud-run-container-image: us-central1-docker.pkg.dev/icalialabs-production/app/workspace-icalialabs-com-backend@${{ needs.google-test-and-build.outputs.container-image-digest }}
#       cloud-run-minimum-instances: 1
#       potentia-host: workspace-potentia-host:latest
#       github_projects_token: operations-github-token:latest
#       gcloud_service_account: github-actions-runner@icalialabs-production.iam.gserviceaccount.com
#       gcloud_workload_identity_provider: projects/461892963202/locations/global/workloadIdentityPools/ci-workload-pool/providers/github
#       gcloud_project: icalialabs-production
#     secrets: inherit
